version: '3.8'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"  # DHCP (optional)
      - "1235:80/tcp"  # Web interface
    environment:
      TZ: 'America/Denver'  # Change to your timezone
      WEBPASSWORD: 'cFyFrVe3KpJcWz'  # Change this!
      PIHOLE_DNS_: '1.1.1.1;1.0.0.1'  # Upstream DNS servers (Cloudflare)
      # Alternative upstream DNS options:
      # PIHOLE_DNS_: '8.8.8.8;8.8.4.4'  # Google DNS
      # PIHOLE_DNS_: '9.9.9.9;149.112.112.112'  # Quad9 DNS
      DNSMASQ_LISTENING: 'all'
      VIRTUAL_HOST: 'pihole.local'  # Optional: custom hostname
      WEBTHEME: 'default-dark'  # Optional: dark theme
      REV_SERVER: 'true'  # Enable reverse DNS lookups
      REV_SERVER_DOMAIN: 'local'  # Your local domain
      REV_SERVER_TARGET: '192.168.1.1'  # Your router's IP
      REV_SERVER_CIDR: '192.168.1.0/24'  # Your network CIDR
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
