version: "3.9"

services:
  db:
    image: mariadb:11
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: secretpw
    volumes:
      - /mnt/nas/nextcloud_db:/var/lib/mysql
    networks:
      - internal

  nextcloud:
    image: nextcloud:29
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: secretpw
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: adminpass
      NEXTCLOUD_TRUSTED_DOMAINS: |
        drive.thelennons.co
        192.168.1.180:8080
        localhost
    volumes:
      - /mnt/nas/nextcloud_app:/var/www/html/data
    networks:
      - internal
      - proxy

networks:
  internal:
    name: internal
    driver: bridge
  proxy:
    external: true

