version: "3.9"

services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    restart: unless-stopped
    environment:
      EULA: "TRUE"        # Must accept Mojang’s EULA
      TYPE: "VANILLA"     # Java Edition “vanilla”; change to PAPER or SPIGOT if you prefer
      MEMORY: "2G"        # Adjust to suit your server RAM
    volumes:
      - ./data:/data      # Where world, logs, settings live
    ports:
      - "25565:25565"     # Expose container port, so host:25565 → mc:25565
    networks:
      - proxy             # Join your existing `proxy` network

networks:
  proxy:
    external: true

